ACCEL_ASCII "E:\Yra\KPK_5\Hard\Pcad\main_board\Производство\14.02.2014\Определение КЗ в цепях питания\src\images\stend.sch"

(asciiHeader 
  (asciiVersion 3 0)
  (timeStamp 2014 2 19 9 21 14)
  (program "P-CAD 2006 Schematic" "19.02.9589")
  (copyright "Copyright © 1992-2006 Altium Limited")
  (fileAuthor "   ")
  (headerString "")
  (fileUnits mm)
  (guidString "{0BBD4008-C1AE-43AE-8E77-5B615CD1C533}")
)

(library "Library_1"
  (textStyleDef "(Default)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 2.54)
      (strokeWidth 0.254)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(PinStyle)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 2.3114)
      (strokeWidth 0.2286)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(PartStyle)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.4798)
      (strokeWidth 0.3556)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(WireStyle)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 1.524)
      (strokeWidth 0.2286)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(PortStyle)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 3.302)
      (strokeWidth 0.2286)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 204)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 38)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(DefaultTTF)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 2.54)
      (strokeWidth 0.254)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Arial")
      (fontHeight 3.175)
      (strokeWidth 0.19843)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(PinStyle) [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 2.3114)
      (strokeWidth 0.1)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(PartStyle) [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.4798)
      (strokeWidth 0.1)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(WireStyle) [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 1.524)
      (strokeWidth 0.1)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(PortStyle) [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 1.524)
      (strokeWidth 0.1)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "GostB-12"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 3.048)
      (strokeWidth 0.3048)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 38)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "GostB-14"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 3.556)
      (strokeWidth 0.3556)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.93889)
      (strokeWidth 0.30868)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 38)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "GostB-18"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 4.572)
      (strokeWidth 0.4572)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 6.35)
      (strokeWidth 0.39687)
      (fontWeight 400)
      (fontCharSet 204)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 38)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "T:H157W15"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.5)
      (strokeWidth 0.1)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "T:H98W9"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 2.5)
      (strokeWidth 0.1)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "text3"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.0)
      (strokeWidth 0.1)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "text3.5"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.5)
      (strokeWidth 0.1)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "text4"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 4.0)
      (strokeWidth 0.1)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "text5"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 5.0)
      (strokeWidth 0.1)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "text7"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 7.0)
      (strokeWidth 0.2)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "gost18"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.5)
      (strokeWidth 0.1)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 6.35)
      (strokeWidth 0.39687)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "gost16"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.5)
      (strokeWidth 0.1)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 5.64444)
      (strokeWidth 0.35277)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "gost14"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.5)
      (strokeWidth 0.1)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.93889)
      (strokeWidth 0.30868)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "gost12"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.5)
      (strokeWidth 0.1)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "gost9"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.5)
      (strokeWidth 0.1)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 3.175)
      (strokeWidth 0.19843)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "gost11"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.5)
      (strokeWidth 0.1)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 3.88056)
      (strokeWidth 0.24253)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "P16"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "BASIC_P")
      (fontHeight 5.0)
      (strokeWidth 0.15)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "T:H157W15 [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.5)
      (strokeWidth 0.1)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "T:H98W9 [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.5)
      (strokeWidth 0.1)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "title"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 4.5)
      (strokeWidth 0.1)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 6.35)
      (strokeWidth 0.39687)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "author"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.0)
      (strokeWidth 0.1)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "data"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 2.0)
      (strokeWidth 0.1)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "number"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 5.0)
      (strokeWidth 0.1)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "P16 [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "BASIC_P")
      (fontHeight 5.0)
      (strokeWidth 0.3)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "P16 [2]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "BASIC_P")
      (fontHeight 5.0)
      (strokeWidth 0.15)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "GostB-12 [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 3.048)
      (strokeWidth 0.3048)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "GostB-18 [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 4.572)
      (strokeWidth 0.4572)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 6.35)
      (strokeWidth 0.39687)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "GostB-16"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 4.064)
      (strokeWidth 0.4064)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 5.64444)
      (strokeWidth 0.35277)
      (fontWeight 400)
      (fontCharSet 204)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 38)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "GostB-16 [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 4.064)
      (strokeWidth 0.4064)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 5.64444)
      (strokeWidth 0.35277)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(ESCD)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 2.54)
      (strokeWidth 0.254)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Arial")
      (fontHeight 3.52778)
      (strokeWidth 0.22048)
      (fontWeight 400)
      (fontCharSet 204)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 38)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(PinStyle) (3)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 2.3114)
      (strokeWidth 0.2286)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.93889)
      (strokeWidth 0.30868)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(RussianTTF)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 2.54)
      (strokeWidth 0.254)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type A")
      (fontHeight 3.175)
      (strokeWidth 0.19843)
      (fontWeight 300)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(RussianTTF-2)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 2.54)
      (strokeWidth 0.254)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Arial")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 204)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 38)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(RussianTTF-3)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 2.54)
      (strokeWidth 0.254)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Arial")
      (fontHeight 5.64444)
      (strokeWidth 0.35277)
      (fontWeight 400)
      (fontCharSet 204)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 38)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(Arial_2.0)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 2.54)
      (strokeWidth 0.254)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Arial")
      (fontHeight 2.0)
      (strokeWidth 0.125)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(PinStyle)(22)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 4.0)
      (strokeWidth 0.1)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 4.0)
      (strokeWidth 0.25)
      (fontWeight 400)
      (fontCharSet 204)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 22)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(PartStyle)(10)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 3.4798)
      (strokeWidth 0.3556)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 3.52778)
      (strokeWidth 0.22048)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 38)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(partstyle)(11)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 4.5)
      (strokeWidth 0.2)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "gost12 [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 3.5)
      (strokeWidth 0.1)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 204)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 38)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "gost18 [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.5)
      (strokeWidth 0.1)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 6.35)
      (strokeWidth 0.39687)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(PinStyle) [2]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 3.048)
      (strokeWidth 0.3048)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(DefaultTTF) [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 3.048)
      (strokeWidth 0.3048)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(PinStyle) [3]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 2.3114)
      (strokeWidth 0.2286)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "GostB-14 [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 3.556)
      (strokeWidth 0.3556)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.93889)
      (strokeWidth 0.30868)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "GostB-10"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 3.048)
      (strokeWidth 0.3048)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 3.52778)
      (strokeWidth 0.22048)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 38)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "GostB-11"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 3.048)
      (strokeWidth 0.3048)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 3.88056)
      (strokeWidth 0.24253)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "Rotated-18"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "BASIC_P")
      (fontHeight 6.0)
      (strokeWidth 0.3048)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "H4.00"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 4.0)
      (strokeWidth 0.25)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Arial")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 204)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 38)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(DefaultTTF) [2]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 2.54)
      (strokeWidth 0.254)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Arial")
      (fontHeight 3.175)
      (strokeWidth 0.19843)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(Default) [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 2.54)
      (strokeWidth 0.254)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(PinStyle) [4]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 2.3114)
      (strokeWidth 0.1)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (symbolDef "A_BLOCK_1"
    (originalName "A_BLOCK")
    (attr "Type" "" (pt 5.08 0.0) (justify UpperCenter) (textStyleRef "GostB-12") )
    (attr "RefDes" "" (pt 5.08 1.27) (isVisible True) (justify LowerCenter) (textStyleRef "GostB-12") )
    (attr "Value" "" (textStyleRef "GostB-12") )
  )
  (symbolDef "A_BLOCK_2"
    (originalName "A_BLOCK")
    (attr "Type" "" (pt 5.08 0.0) (justify UpperCenter) (textStyleRef "GostB-12") )
    (attr "RefDes" "" (pt 5.08 1.27) (isVisible True) (justify LowerCenter) (textStyleRef "GostB-12") )
    (attr "Value" "" (textStyleRef "GostB-12") )
  )
  (symbolDef "A_BLOCK_3"
    (originalName "A_BLOCK")
    (attr "Type" "" (pt 5.08 0.0) (justify UpperCenter) (textStyleRef "GostB-12") )
    (attr "RefDes" "" (pt 5.08 1.27) (isVisible True) (justify LowerCenter) (textStyleRef "GostB-12") )
    (attr "Value" "" (textStyleRef "GostB-12") )
  )
  (compDef "A_BLOCK_1"
    (originalName "A_BLOCK")
    (compHeader 
      (sourceLibrary "STEPAN.LIB")
      (numPins 0)
      (numParts 1)
      (alts (ieeeAlt False) (deMorganAlt False))
      (refDesPrefix "A")
    )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "A_BLOCK") )
  )
)

(netlist "Netlist_1"
  (compInst "G1"
    (compRef "A_BLOCK_1")
    (originalName "A_BLOCK")
    (compValue "\\Источник питания Б5-71\\ЕЭ3.233.316 ТУ")
  )
  (compInst "P3"
    (compRef "A_BLOCK_1")
    (originalName "A_BLOCK")
    (compValue "\\Осциллограф АСК-2168\\АКТАКОМ")
  )
  (compInst "R1"
    (compRef "A_BLOCK_1")
    (originalName "A_BLOCK")
  )
)

(schematicDesign "SchDesign_1"
  (schDesignHeader 
    (workspaceSize 1189.0 841.0)
    (gridDfns 
      (grid "0.100")
      (grid "0.254")
      (grid "0.508")
      (grid "1.270")
      (grid "2.540")
    )
    (designInfo 
      (fieldSet "(Default)"
        (fieldDef "Date" "  ")
        (fieldDef "Time" "   ")
        (fieldDef "Author" "   ")
        (fieldDef "Revision" "  ")
        (fieldDef "Title" " ")
        (fieldDef "Approved By" "  ")
        (fieldDef "Checked By" "   ")
        (fieldDef "Company Name" "   ")
        (fieldDef "Drawing Number" "   ")
        (fieldDef "Drawn By" "   ")
        (fieldDef "Engineer" "   ")
        (fieldDef "Variant Name" "")
        (fieldDef "Variant Description" "")
        (fieldDef "Engineer1" "  ")
        (fieldDef "Title1" " ")
        (fieldDef "Дата" "  ")
        (fieldDef "Дец. номер 1" "  ")
        (fieldDef "Дец. номер 2" "  ")
        (fieldDef "Копировал" "  ")
        (fieldDef "Лист" "  ")
        (fieldDef "Листов" "  ")
        (fieldDef "Н. контр." "  ")
        (fieldDef "Наим. изд 1" "  ")
        (fieldDef "Наим. изд. 2" "  ")
        (fieldDef "Наименов. документа" "  ")
        (fieldDef "Пров." "  ")
        (fieldDef "Разраб." "  ")
        (fieldDef "Утв." "  ")
      )
      (fieldSet "Field Set 1"
        (fieldDef "Date" "")
        (fieldDef "Time" "")
        (fieldDef "Author" "")
        (fieldDef "Revision" "")
        (fieldDef "Title" "")
        (fieldDef "Approved By" "")
        (fieldDef "Checked By" "")
        (fieldDef "Company Name" "")
        (fieldDef "Drawing Number" "")
        (fieldDef "Drawn By" "")
        (fieldDef "Engineer" "")
        (fieldDef "Variant Name" "")
        (fieldDef "Variant Description" "")
        (fieldDef "Engineer1" "")
        (fieldDef "Title1" "")
        (fieldDef "Дата" "")
        (fieldDef "Дец. номер 1" "")
        (fieldDef "Дец. номер 2" "")
        (fieldDef "Копировал" "")
        (fieldDef "Лист" "")
        (fieldDef "Листов" "")
        (fieldDef "Н. контр." "")
        (fieldDef "Наим. изд 1" "")
        (fieldDef "Наим. изд. 2" "")
        (fieldDef "Наименов. документа" "")
        (fieldDef "Пров." "")
        (fieldDef "Разраб." "")
        (fieldDef "Утв." "")
      )
      (fieldSet "Field Set 2"
        (fieldDef "Date" "")
        (fieldDef "Time" "")
        (fieldDef "Author" "")
        (fieldDef "Revision" "")
        (fieldDef "Title" "")
        (fieldDef "Approved By" "")
        (fieldDef "Checked By" "")
        (fieldDef "Company Name" "")
        (fieldDef "Drawing Number" "")
        (fieldDef "Drawn By" "")
        (fieldDef "Engineer" "")
        (fieldDef "Variant Name" "")
        (fieldDef "Variant Description" "")
        (fieldDef "Engineer1" "")
        (fieldDef "Title1" "")
        (fieldDef "Дата" "")
        (fieldDef "Дец. номер 1" "")
        (fieldDef "Дец. номер 2" "")
        (fieldDef "Копировал" "")
        (fieldDef "Лист" "")
        (fieldDef "Листов" "")
        (fieldDef "Н. контр." "")
        (fieldDef "Наим. изд 1" "")
        (fieldDef "Наим. изд. 2" "")
        (fieldDef "Наименов. документа" "")
        (fieldDef "Пров." "")
        (fieldDef "Разраб." "")
        (fieldDef "Утв." "")
      )
    )
    (refPointSize 2.54)
    (infoPointSize 2.54)
    (junctionSize 1.0)
    (refPointSizePrint 2.54)
    (infoPointSizePrint 2.54)
    (junctionSizePrint 1.0)
  )
  (titleSheet 
     ""
    1.0000 
    (isVisible True)
    (offset 0.0 0.0)
    (border
      (isVisible False)
      (height 815.6)
      (width 1163.6)
      (offset 12.7 12.7)
    )
    (zones
      (isVisible False) 
      (textStyleRef "GostB-12") 
      (horizontalZones 1
        (numDirection ascending)
        (numType Alphabetic)
      )
      (verticalZones 1 
        (numDirection ascending)
        (numType Numeric)
      ) 
    ) 
  )
  (sheet "Sheet1" (sheetNum 1)
    (fieldSetRef "(Default)")
    (triplePointArc (pt 187.96 568.96) (pt 187.96 569.26) (pt 187.96 569.26) (width 1.27) )
    (triplePointArc (pt 185.42 642.62) (pt 185.42 643.22) (pt 185.42 643.22) (width 1.27) )
    (line (pt 200.66 568.96) (pt 204.47 568.96) )
    (line (pt 200.66 574.04) (pt 204.47 574.04) )
    (line (pt 200.66 645.16) (pt 204.47 645.16) )
    (triplePointArc (pt 208.28 574.04) (pt 208.28 574.34) (pt 208.28 574.34) (width 1.27) )
    (line (pt 216.44 581.47) (pt 220.44 581.47) )
    (line (pt 220.44 591.47) (pt 216.44 591.47) )
    (triplePointArc (pt 215.9 604.52) (pt 215.9 604.82) (pt 215.9 604.82) (width 1.27) )
    (line (pt 215.9 618.49) (pt 215.9 622.3) )
    (line (pt 215.9 633.73) (pt 215.9 637.54) )
    (symbol (symbolRef "A_BLOCK_1") (refDesRef "R1") (partNum 1) (pt 219.71 586.74) )
    (line (pt 229.87 591.82) (pt 229.87 589.28) (width 0.7) )
    (triplePointArc (pt 248.92 604.52) (pt 248.92 604.82) (pt 248.92 604.82) (width 1.27) )
    (line (pt 311.15 610.87) (pt 311.15 613.41) (width 0.7) )
    (triplePointArc (pt 185.42 571.5) (pt 185.42 572.1) (pt 185.42 572.1) (width 1.27) )
    (text (pt 184.15 577.85) "X1" (textStyleRef "GostB-12") (extent 4.49791 5.02707) )
    (triplePointArc (pt 187.96 640.08) (pt 187.96 640.28) (pt 187.96 640.28) (width 1.27) )
    (line (pt 200.66 640.08) (pt 204.47 640.08) )
    (triplePointArc (pt 218.44 571.5) (pt 218.44 571.8) (pt 218.44 571.8) (width 1.27) )
    (line (pt 218.44 581.47) (pt 218.44 571.5) )
    (line (pt 215.9 601.98) (pt 215.9 607.06) )
    (line (pt 215.9 608.33) (pt 215.9 612.14) )
    (line (pt 215.9 623.57) (pt 215.9 627.38) )
    (line (pt 215.9 628.65) (pt 215.9 632.46) )
    (line (pt 215.9 638.81) (pt 215.9 640.08) )
    (text (pt 275.59 615.95) "А1" (textStyleRef "GostB-12") (extent 4.49791 5.02707) )
    (line (pt 199.39 551.18) (pt 199.39 610.87) (width 0.7) )
    (line (pt 208.28 604.52) (pt 208.28 574.04) )
    (line (pt 216.44 591.47) (pt 216.44 581.47) )
    (line (pt 215.9 613.41) (pt 215.9 617.22) )
    (line (pt 220.44 581.47) (pt 220.44 591.47) )
    (line (pt 199.39 622.3) (pt 199.39 681.99) (width 0.7) )
    (line (pt 218.44 591.47) (pt 218.44 642.62) )
    (triplePointArc (pt 175.26 557.53) (pt 174.36585 557.97776) (pt 174.36585 557.97776) (width 0.254) )
    (line (pt 160.02 557.53) (pt 175.26 557.53) )
    (text (pt 168.91 572.77) "\"10 MОм\"" (textStyleRef "GostB-12") (extent 15.08124 5.02707) )
    (symbol (symbolRef "A_BLOCK_2") (refDesRef "P3") (partNum 1) (pt 177.79 610.89) )
    (triplePointArc (pt 175.26 628.65) (pt 174.36585 629.09776) (pt 174.36585 629.09776) (width 0.254) )
    (line (pt 160.02 628.65) (pt 175.26 628.65) )
    (line (pt 205.74 568.96) (pt 210.82 568.96) )
    (line (pt 194.31 568.96) (pt 199.39 568.96) )
    (line (pt 187.96 568.96) (pt 193.04 568.96) )
    (line (pt 190.5 574.04) (pt 193.04 574.04) )
    (line (pt 205.74 574.04) (pt 210.82 574.04) )
    (line (pt 194.31 574.04) (pt 199.39 574.04) )
    (line (pt 215.9 604.52) (pt 208.28 604.52) )
    (line (pt 190.5 645.16) (pt 193.04 645.16) )
    (line (pt 205.74 645.16) (pt 209.55 645.16) )
    (line (pt 194.31 645.16) (pt 199.39 645.16) )
    (line (pt 210.82 645.16) (pt 214.63 645.16) )
    (text (pt 222.25 580.39) "680 Ом " (textStyleRef "GostB-14") (extent 14.68437 5.86493) )
    (line (pt 224.79 598.17) (pt 232.41 598.17) (width 0.554) )
    (triplePointArc (pt 220.98 604.52) (pt 220.98 604.82) (pt 220.98 604.82) (width 1.27) )
    (triplePointArc (pt 228.6 604.52) (pt 228.6 604.82) (pt 228.6 604.82) (width 1.27) )
    (line (pt 228.6 604.52) (pt 220.98 604.52) )
    (line (pt 220.98 618.49) (pt 220.98 622.3) )
    (line (pt 220.98 633.73) (pt 220.98 637.54) )
    (line (pt 220.98 645.16) (pt 220.98 643.89) )
    (line (pt 289.56 589.28) (pt 289.56 591.82) (width 0.7) )
    (text (pt 170.18 560.07) "\"Корпус\"" (textStyleRef "GostB-12") (extent 14.55207 5.02707) )
    (line (pt 160.02 628.65) (pt 160.02 622.3) )
    (text (pt 170.18 631.19) "\"Корпус\"" (textStyleRef "GostB-12") (extent 14.55207 5.02707) )
    (symbol (symbolRef "A_BLOCK_3") (refDesRef "G1") (partNum 1) (pt 176.53 681.99) )
    (line (pt 205.74 640.08) (pt 209.55 640.08) )
    (line (pt 194.31 640.08) (pt 199.39 640.08) )
    (line (pt 187.96 640.08) (pt 193.04 640.08) )
    (line (pt 210.82 640.08) (pt 215.9 640.08) )
    (line (pt 242.57 580.39) (pt 236.22 574.04) (width 0.7) )
    (line (pt 220.98 601.98) (pt 220.98 607.06) )
    (line (pt 220.98 608.33) (pt 220.98 612.14) )
    (line (pt 228.6 604.52) (pt 228.6 598.17) )
    (line (pt 220.98 623.57) (pt 220.98 627.38) )
    (line (pt 220.98 628.65) (pt 220.98 632.46) )
    (line (pt 220.98 638.81) (pt 220.98 642.62) )
    (text (pt 248.92 605.79) "GND" (textStyleRef "GostB-14") (extent 8.33437 5.86493) )
    (text (pt 279.4 607.06) "Изделие" (textStyleRef "GostB-14") (extent 16.27187 5.86493) )
    (line (pt 160.02 557.53) (pt 160.02 551.18) )
    (line (pt 167.64 610.87) (pt 167.64 551.18) (width 0.7) )
    (text (pt 168.91 640.08) "\"50 Ом\"" (textStyleRef "GostB-12") (extent 13.22916 5.02707) )
    (line (pt 220.98 613.41) (pt 220.98 617.22) )
    (line (pt 233.68 571.5) (pt 246.38 584.2) )
    (line (pt 167.64 681.99) (pt 167.64 622.3) (width 0.7) )
    (line (pt 156.21 551.18) (pt 163.83 551.18) (width 0.554) )
    (line (pt 167.64 551.18) (pt 199.39 551.18) (width 0.7) )
    (line (pt 228.6 604.52) (pt 248.92 604.52) )
    (line (pt 199.39 610.87) (pt 167.64 610.87) (width 0.7) )
    (line (pt 156.21 622.3) (pt 163.83 622.3) (width 0.554) )
    (line (pt 167.64 622.3) (pt 199.39 622.3) (width 0.7) )
    (line (pt 220.98 645.16) (pt 215.9 645.16) )
    (line (pt 185.42 642.62) (pt 218.44 642.62) )
    (line (pt 199.39 681.99) (pt 167.64 681.99) (width 0.7) )
    (triplePointArc (pt 185.42 571.5) (pt 182.88 574.04) (pt 182.88 574.04) (width 0.254) )
    (line (pt 185.42 571.5) (pt 233.68 571.5) )
    (text (pt 168.91 591.82) "Осциллограф\r\n(mВ/дел. =50,\r\nвход = открытый,\r\nФНЧ <20 MGz)" (textStyleRef "GostB-12") (extent 30.42707 17.72706) )
    (text (pt 182.88 647.7) "X1" (textStyleRef "GostB-12") (extent 4.49791 5.02707) )
    (line (pt 289.56 589.28) (pt 311.15 610.87) (width 0.7) )
    (line (pt 251.46 613.41) (pt 229.87 591.82) (width 0.7) )
    (text (pt 247.65 577.85) "Иголка " (textStyleRef "GostB-14") (extent 14.15521 5.86493) )
    (triplePointArc (pt 185.42 642.62) (pt 182.88 645.16) (pt 182.88 645.16) (width 0.254) )
    (text (pt 168.91 655.32) "Генератор\r\nпрямоугольных\r\nимпульсов\r\n(мин. =0 В,\r\nмакс. = 100 mВ,\r\nчастота = 100 Гц)" (textStyleRef "GostB-12") (extent 31.22082 26.19372) )
    (line (pt 311.15 613.41) (pt 289.56 591.82) (width 0.7) )
    (line (pt 229.87 589.28) (pt 289.56 589.28) (width 0.7) )
    (line (pt 229.87 591.82) (pt 289.56 591.82) (width 0.7) )
    (line (pt 251.46 613.41) (pt 311.15 613.41) (width 0.7) )
    (drawBorder True)
    (EntireDesign True)
    (isRotated False)
    (pageSize Size_A)
    (scaleFactor  1.00)
    (offset 0.0 0.0)
    (PrintRegion 
      (pt 0.0 0.0) (pt 0.0 0.0) )
    (sheetOrderNum 1)
  )
  (schematicPrintSettings 
    (sheetList 
      (sheetRef 1)
    )
  )

  (programState 
    (gridState 
      (currentAbsGrid "0.100")
      (currentRelGrid "2.540")
      (isAbsoluteGrid True)
      (isDottedGrid True)
      (isVisibleGrid True)
      (isPromptForRel False)
    )
    (ecoState (ecoRecording False))
    (currentTextStyle "GostB-14")
  )

  (reportSettings 
    (reportStyle reportStyleComma)
    (reportDestination DestinationScreen)
    (pt 0.0 0.0) 
    (reportDefinitions 
      (reportDefinition 
        (reportName "Attributes")
        (reportExtension "atr")
        (reportType ReportTypeAttributes)
        (reportLinesPerPage 70)
        (reportColumnWidth 20)
        (reportHeader "")
        (reportFooter "")
        (reportShowCDFPreface True)
        (reportShowColumnNames True)
        (reportFieldsSections 
          (reportFields 
            (reportField 
              (reportFieldName "RefDes")
              (reportFieldType PropertyTypeRefdes)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 6)
            )
            (reportField 
              (reportFieldName "Type")
              (reportFieldType PropertyTypeType)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 4)
            )
            (reportField 
              (reportFieldName "Value")
              (reportFieldType PropertyTypeCompValue)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 5)
            )
          )
          (reportFields 
            (reportField 
              (reportFieldName "NetName")
              (reportFieldType PropertyTypeNetname)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 7)
            )
          )
        )
      )
      (reportDefinition 
        (reportName "Bill of Materials")
        (reportExtension "bom")
        (reportShowFlag True)
        (reportType ReportTypeBillOfMaterials)
        (reportLinesPerPage 62)
        (reportColumnWidth 15)
        (reportHeader "")
        (reportFooter "")
        (reportShowCDFPreface True)
        (reportShowColumnNames True)
        (reportFieldsSections 
          (reportFields 
            (reportField 
              (reportFieldName "RefDes")
              (reportFieldType PropertyTypeRefdes)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 6)
            )
            (reportField 
              (reportFieldName "_Count")
              (reportFieldType PropertyTypeCount)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 6)
            )
            (reportField 
              (reportFieldName "ComponentName")
              (reportFieldType PropertyTypeComponentName)
              (reportFieldSortOrder 2)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 13)
            )
            (reportField 
              (reportFieldName "PatternName")
              (reportFieldType PropertyTypePatternName)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldColumnWidth 11)
            )
            (reportField 
              (reportFieldName "Value")
              (reportFieldType PropertyTypeCompValue)
              (reportFieldSortOrder 3)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 5)
            )
            (reportField 
              (reportFieldName "Plus")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldColumnWidth 4)
            )
          )
        )
      )
      (reportDefinition 
        (reportName "Global Nets")
        (reportExtension "gnr")
        (reportType ReportTypeGlobalNets)
        (reportLinesPerPage 62)
        (reportColumnWidth 15)
        (reportHeader "")
        (reportFooter "")
        (reportShowCDFPreface True)
        (reportShowColumnNames True)
        (reportFieldsSections 
          (reportFields 
            (reportField 
              (reportFieldName "NetName")
              (reportFieldType PropertyTypeNetname)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 7)
            )
            (reportField 
              (reportFieldName "SheetNum")
              (reportFieldType PropertyTypeSheetnumber)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 8)
            )
          )
        )
      )
      (reportDefinition 
        (reportName "Last Used RefDes")
        (reportExtension "lud")
        (reportType ReportTypeLastRefdes)
        (reportLinesPerPage 62)
        (reportColumnWidth 15)
        (reportHeader "")
        (reportFooter "")
        (reportShowCDFPreface True)
        (reportShowColumnNames True)
        (reportFieldsSections 
          (reportFields 
            (reportField 
              (reportFieldName "RefDes")
              (reportFieldType PropertyTypeRefdes)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 6)
            )
            (reportField 
              (reportFieldName "Value")
              (reportFieldType PropertyTypeCompValue)
              (reportFieldSortOrder 2)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 5)
            )
          )
        )
      )
      (reportDefinition 
        (reportName "Library Contents")
        (reportExtension "lct")
        (reportType ReportTypeLibrary)
        (reportLinesPerPage 62)
        (reportColumnWidth 15)
        (reportHeader "")
        (reportFooter "")
        (reportShowCDFPreface True)
        (reportShowColumnNames True)
      )
      (reportDefinition 
        (reportName "Parts Locations")
        (reportExtension "plc")
        (reportType ReportTypePartsLocations)
        (reportLinesPerPage 62)
        (reportColumnWidth 15)
        (reportHeader "")
        (reportFooter "")
        (reportShowCDFPreface True)
        (reportShowColumnNames True)
        (reportFieldsSections 
          (reportFields 
            (reportField 
              (reportFieldName "RefDes")
              (reportFieldType PropertyTypeRefdes)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 6)
            )
            (reportField 
              (reportFieldName "SheetNum")
              (reportFieldType PropertyTypeSheetnumber)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 8)
            )
            (reportField 
              (reportFieldName "LocationX")
              (reportFieldType PropertyTypeLocationX)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 9)
            )
            (reportField 
              (reportFieldName "LocationY")
              (reportFieldType PropertyTypeLocationY)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 9)
            )
            (reportField 
              (reportFieldName "Rotation")
              (reportFieldType PropertyTypeRotation)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 8)
            )
          )
        )
      )
      (reportDefinition 
        (reportName "Parts Usage")
        (reportExtension "ptu")
        (reportType ReportTypePartsUsage)
        (reportLinesPerPage 62)
        (reportColumnWidth 15)
        (reportHeader "")
        (reportFooter "")
        (reportShowCDFPreface True)
        (reportShowColumnNames True)
        (reportFieldsSections 
          (reportFields 
            (reportField 
              (reportFieldName "RefDes")
              (reportFieldType PropertyTypeRefdes)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 6)
            )
            (reportField 
              (reportFieldName "Type")
              (reportFieldType PropertyTypeType)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 4)
            )
            (reportField 
              (reportFieldName "Unused Parts")
              (reportFieldType PropertyTypeUnusedParts)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 12)
            )
            (reportField 
              (reportFieldName "ComponentLibrary")
              (reportFieldType PropertyTypeComponentLibrary)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 16)
            )
          )
        )
      )
      (reportDefinition 
        (reportName "Variant")
        (reportExtension "var")
        (reportType ReportTypeVariant)
        (reportLinesPerPage 60)
        (reportColumnWidth 35)
        (reportHeader "")
        (reportFooter "")
        (reportShowCDFPreface True)
        (reportShowColumnNames True)
        (reportFieldsSections 
          (reportFields 
            (reportField 
              (reportFieldName "Variant")
              (reportFieldType PropertyTypeVariant)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 7)
            )
            (reportField 
              (reportFieldName "Variant Decription")
              (reportFieldType PropertyTypeVariantDescription)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 18)
            )
            (reportField 
              (reportFieldName "Variant Excluded Components")
              (reportFieldType PropertyTypeExcludedComponents)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 27)
            )
          )
        )
      )
    )
  )
)
