ACCEL_ASCII "D:\yra\LaTeX\eskdi\about\src\A4_v_example.sch"

(asciiHeader 
  (asciiVersion 3 0)
  (timeStamp 2014 4 7 22 42 29)
  (program "P-CAD 2006 Schematic" "19.02.9589")
  (copyright "Copyright © 1992-2006 Altium Limited")
  (fileAuthor "  ")
  (headerString "")
  (fileUnits mm)
  (guidString "{AC494693-7162-4AE5-9C9E-BEA91037FC90}")
)

(library "Library_1"
  (textStyleDef "(Default)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 2.54)
      (strokeWidth 0.254)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(PinStyle)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 2.3114)
      (strokeWidth 0.2286)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(PartStyle)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.4798)
      (strokeWidth 0.3556)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(WireStyle)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 1.524)
      (strokeWidth 0.2286)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(PortStyle)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 3.302)
      (strokeWidth 0.2286)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(DefaultTTF)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 2.54)
      (strokeWidth 0.254)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Arial")
      (fontHeight 3.175)
      (strokeWidth 0.19843)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(PinStyle) [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 2.3114)
      (strokeWidth 0.1)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(PartStyle) [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.4798)
      (strokeWidth 0.1)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(WireStyle) [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 1.524)
      (strokeWidth 0.1)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(PortStyle) [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 1.524)
      (strokeWidth 0.1)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "GostB-12"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 3.048)
      (strokeWidth 0.3048)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "GostB-14"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 3.556)
      (strokeWidth 0.3556)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.93889)
      (strokeWidth 0.30868)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "GostB-18"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 4.572)
      (strokeWidth 0.4572)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 6.35)
      (strokeWidth 0.39687)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "T:H157W15"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.5)
      (strokeWidth 0.1)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "T:H98W9"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 2.5)
      (strokeWidth 0.1)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "title"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 4.5)
      (strokeWidth 0.1)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 6.35)
      (strokeWidth 0.39687)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "author"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.0)
      (strokeWidth 0.1)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "data"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 2.0)
      (strokeWidth 0.1)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "number"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 5.0)
      (strokeWidth 0.1)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "gost11"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.5)
      (strokeWidth 0.1)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 3.88056)
      (strokeWidth 0.24253)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "gost9"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.5)
      (strokeWidth 0.1)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 3.175)
      (strokeWidth 0.19843)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "gost12"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.5)
      (strokeWidth 0.1)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "gost14"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.5)
      (strokeWidth 0.1)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.93889)
      (strokeWidth 0.30868)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "gost18"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.5)
      (strokeWidth 0.1)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 6.35)
      (strokeWidth 0.39687)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "gost16"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.5)
      (strokeWidth 0.1)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 5.64444)
      (strokeWidth 0.35277)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "P16"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "BASIC_P")
      (fontHeight 5.0)
      (strokeWidth 0.15)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "P16 [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "BASIC_P")
      (fontHeight 5.0)
      (strokeWidth 0.3)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "T:H157W15 [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.5)
      (strokeWidth 0.1)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "T:H98W9 [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.5)
      (strokeWidth 0.1)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "P16 [2]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "BASIC_P")
      (fontHeight 5.0)
      (strokeWidth 0.15)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "GostB-11"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 3.048)
      (strokeWidth 0.3048)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 3.88056)
      (strokeWidth 0.24253)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "GostB-10"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 3.048)
      (strokeWidth 0.3048)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 3.5)
      (strokeWidth 0.21875)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "GostB-16"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 4.064)
      (strokeWidth 0.4064)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 5.64444)
      (strokeWidth 0.35277)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "text3"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.0)
      (strokeWidth 0.1)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(ESCD)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 2.54)
      (strokeWidth 0.254)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Arial")
      (fontHeight 3.52778)
      (strokeWidth 0.22048)
      (fontWeight 400)
      (fontCharSet 204)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 38)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(PinStyle) (3)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 2.3114)
      (strokeWidth 0.2286)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.93889)
      (strokeWidth 0.30868)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(RussianTTF)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 2.54)
      (strokeWidth 0.254)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type A")
      (fontHeight 3.175)
      (strokeWidth 0.19843)
      (fontWeight 300)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(RussianTTF-2)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 2.54)
      (strokeWidth 0.254)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Arial")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 204)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 38)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(RussianTTF-3)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 2.54)
      (strokeWidth 0.254)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Arial")
      (fontHeight 5.64444)
      (strokeWidth 0.35277)
      (fontWeight 400)
      (fontCharSet 204)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 38)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "GostB-12 [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 3.048)
      (strokeWidth 0.3048)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 204)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 38)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(Arial_2.0)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 2.54)
      (strokeWidth 0.254)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Arial")
      (fontHeight 2.0)
      (strokeWidth 0.125)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(PinStyle)(22)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 4.0)
      (strokeWidth 0.1)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 4.0)
      (strokeWidth 0.25)
      (fontWeight 400)
      (fontCharSet 204)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 22)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(PartStyle)(10)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 3.4798)
      (strokeWidth 0.3556)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 3.52778)
      (strokeWidth 0.22048)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 38)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "text3.5"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.5)
      (strokeWidth 0.1)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "text4"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 4.0)
      (strokeWidth 0.1)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "text5"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 5.0)
      (strokeWidth 0.1)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "text7"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 7.0)
      (strokeWidth 0.2)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "H4.00"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 4.0)
      (strokeWidth 0.25)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Arial")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 204)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 38)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "GostB-14 [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 3.556)
      (strokeWidth 0.3556)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.93889)
      (strokeWidth 0.30868)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 38)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "GostB-18 [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 4.572)
      (strokeWidth 0.4572)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 6.35)
      (strokeWidth 0.39687)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 38)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "gost12 [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 3.5)
      (strokeWidth 0.1)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 204)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 38)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "GostB-12 [2]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 3.048)
      (strokeWidth 0.3048)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "GostB-18 [2]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 4.572)
      (strokeWidth 0.4572)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 6.35)
      (strokeWidth 0.39687)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "GostB-16 [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 4.064)
      (strokeWidth 0.4064)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 5.64444)
      (strokeWidth 0.35277)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(PinStyle) [2]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 3.048)
      (strokeWidth 0.3048)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "gost11 [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.5)
      (strokeWidth 0.1)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 3.88056)
      (strokeWidth 0.24253)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(DefaultTTF) [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 3.048)
      (strokeWidth 0.3048)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "gost18 [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 3.5)
      (strokeWidth 0.1)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 6.35)
      (strokeWidth 0.39687)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(PinStyle) [3]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 2.3114)
      (strokeWidth 0.2286)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "GostB-14 [2]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 3.556)
      (strokeWidth 0.3556)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.93889)
      (strokeWidth 0.30868)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "GostB-10 [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 3.048)
      (strokeWidth 0.3048)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 3.52778)
      (strokeWidth 0.22048)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 38)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "Rotated-18"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "BASIC_P")
      (fontHeight 6.0)
      (strokeWidth 0.3048)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "GOST type B")
      (fontHeight 4.23333)
      (strokeWidth 0.26458)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 3)
      (fontClipPrecision 2)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(DefaultTTF) [2]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 2.54)
      (strokeWidth 0.254)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Arial")
      (fontHeight 3.175)
      (strokeWidth 0.19843)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(Default) [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 2.54)
      (strokeWidth 0.254)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(PinStyle) [4]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 2.3114)
      (strokeWidth 0.1)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(partstyle)(11)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 4.5)
      (strokeWidth 0.2)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (symbolDef "HL1_3"
    (originalName "HL1")
    (pin (pinNum 1) (pt 2.54 0.0) (rotation 180.0) (pinLength 2.54) 
      (pinDisplay (dispPinDes False) ) 
      (pinDes (text (pt 0.889 0.0) "1" (textStyleRef "GostB-12") (isFlipped True) (extent 2.11666 5.02707) )
      ) 
      (pinName (text (pt 3.048 0.0) "A" (textStyleRef "GostB-12") (isFlipped True) (justify Right) (extent 3.17499 5.02707) )
      ) 
    )
    (pin (pinNum 2) (pt 12.7 0.0) (pinLength 2.54) 
      (pinDisplay (dispPinDes False) ) 
      (pinDes (text (pt 14.351 0.0) "2" (textStyleRef "GostB-12") (extent 2.64582 5.02707) )
      ) 
      (pinName (text (pt 12.192 0.0) "K" (textStyleRef "GostB-12") (justify Right) (extent 2.91041 5.02707) )
      ) 
    )
    (line (pt -1.27 10.668) (pt 0.508 8.128) )
    (line (pt -1.27 10.668) (pt 1.27 8.89) )
    (line (pt 3.556 5.842) (pt -1.27 10.668) )
    (line (pt 5.842 2.54) (pt 5.842 -2.54) )
    (line (pt 10.16 2.54) (pt 10.16 -2.54) )
    (line (pt 10.16 0.0) (pt 5.842 -2.54) )
    (line (pt 5.842 2.54) (pt 10.16 0.0) )
    (line (pt 15.24 0.0) (pt 0.0 0.0) )
    (triplePointArc (pt 7.62 0.0) (pt 2.54 0.0) (pt 2.54 0.0) (width 0.254) )
    (line (pt -3.302 8.89) (pt -0.762 7.112) )
    (line (pt -3.302 8.89) (pt -1.524 6.35) )
    (line (pt 1.524 4.064) (pt -3.302 8.89) )
    (attr "Value" "" (textStyleRef "GostB-12") )
    (attr "Type" "" (pt 7.62 -5.08) (justify UpperCenter) (textStyleRef "GostB-12") )
    (attr "RefDes" "" (pt 6.0 6.0) (isVisible True) (justify LowerCenter) (textStyleRef "GostB-12") )
  )
  (symbolDef "HL1_1"
    (originalName "HL1")
    (pin (pinNum 1) (pt 2.54 0.0) (rotation 180.0) (pinLength 2.54) 
      (pinDisplay (dispPinDes False) ) 
      (pinDes (text (pt 0.889 0.0) "1" (textStyleRef "GostB-12") (isFlipped True) (extent 2.11666 5.02707) )
      ) 
      (pinName (text (pt 3.048 0.0) "A" (textStyleRef "GostB-12") (isFlipped True) (justify Right) (extent 3.17499 5.02707) )
      ) 
    )
    (pin (pinNum 2) (pt 12.7 0.0) (pinLength 2.54) 
      (pinDisplay (dispPinDes False) ) 
      (pinDes (text (pt 14.351 0.0) "2" (textStyleRef "GostB-12") (extent 2.64582 5.02707) )
      ) 
      (pinName (text (pt 12.192 0.0) "K" (textStyleRef "GostB-12") (justify Right) (extent 2.91041 5.02707) )
      ) 
    )
    (line (pt 5.842 2.54) (pt 5.842 -2.54) )
    (line (pt 10.16 2.54) (pt 10.16 -2.54) )
    (line (pt 10.16 0.0) (pt 5.842 -2.54) )
    (line (pt 5.842 2.54) (pt 10.16 0.0) )
    (line (pt 15.24 0.0) (pt 0.0 0.0) )
    (triplePointArc (pt 7.62 0.0) (pt 2.54 0.0) (pt 2.54 0.0) (width 0.254) )
    (line (pt 12.444 5.842) (pt 17.27 10.668) )
    (line (pt 15.476 5.064) (pt 20.302 9.89) )
    (line (pt 20.302 9.89) (pt 17.762 8.112) )
    (line (pt 17.27 10.668) (pt 14.73 8.89) )
    (line (pt 17.27 10.668) (pt 15.492 8.128) )
    (line (pt 20.302 9.89) (pt 18.524 7.35) )
    (attr "Type" "" (pt 7.62 -5.08) (justify UpperCenter) (textStyleRef "GostB-12") )
    (attr "Value" "" (textStyleRef "GostB-12") )
    (attr "RefDes" "" (pt 10.0 6.0) (isVisible True) (justify LowerCenter) (textStyleRef "GostB-12") )
  )
  (symbolDef "HL1_2"
    (originalName "HL1")
    (pin (pinNum 1) (pt 2.54 0.0) (rotation 180.0) (pinLength 2.54) 
      (pinDisplay (dispPinDes False) ) 
      (pinDes (text (pt 0.889 0.0) "1" (textStyleRef "GostB-12") (isFlipped True) (extent 2.11666 5.02707) )
      ) 
      (pinName (text (pt 3.048 0.0) "A" (textStyleRef "GostB-12") (isFlipped True) (justify Right) (extent 3.17499 5.02707) )
      ) 
    )
    (pin (pinNum 2) (pt 12.7 0.0) (pinLength 2.54) 
      (pinDisplay (dispPinDes False) ) 
      (pinDes (text (pt 14.351 0.0) "2" (textStyleRef "GostB-12") (extent 2.64582 5.02707) )
      ) 
      (pinName (text (pt 12.192 0.0) "K" (textStyleRef "GostB-12") (justify Right) (extent 2.91041 5.02707) )
      ) 
    )
    (line (pt 5.842 2.54) (pt 5.842 -2.54) )
    (line (pt 10.16 2.54) (pt 10.16 -2.54) )
    (line (pt 10.16 0.0) (pt 5.842 -2.54) )
    (line (pt 5.842 2.54) (pt 10.16 0.0) )
    (line (pt 15.24 0.0) (pt 0.0 0.0) )
    (triplePointArc (pt 7.62 0.0) (pt 2.54 0.0) (pt 2.54 0.0) (width 0.254) )
    (line (pt 12.444 4.842) (pt 17.27 9.668) )
    (line (pt 15.476 4.064) (pt 20.302 8.89) )
    (line (pt 17.27 9.668) (pt 14.73 7.89) )
    (line (pt 17.27 9.668) (pt 15.492 7.128) )
    (line (pt 20.302 8.89) (pt 17.762 7.112) )
    (line (pt 20.302 8.89) (pt 18.524 6.35) )
    (attr "Type" "" (pt 7.62 -5.08) (justify UpperCenter) (textStyleRef "GostB-12") )
    (attr "Value" "" (textStyleRef "GostB-12") )
    (attr "RefDes" "" (pt 10.0 6.0) (isVisible True) (justify LowerCenter) (textStyleRef "GostB-12") )
  )
  (symbolDef "R_CONST_1"
    (originalName "R_CONST")
    (pin (pinNum 1) (pt 2.54 0.0) (rotation 180.0) (pinLength 2.54) 
      (pinDisplay (dispPinDes False) ) 
      (pinDes (text (pt 0.889 0.0) "1" (textStyleRef "GostB-12") (isFlipped True) (extent 2.11666 5.02707) )
      ) 
      (pinName (text (pt 3.048 0.0) "" (textStyleRef "GostB-12") (isFlipped True) (justify Right) (extent 0.79374 0.79374) )
      ) 
    )
    (pin (pinNum 2) (pt 15.24 0.0) (pinLength 2.54) 
      (pinDisplay (dispPinDes False) ) 
      (pinDes (text (pt 16.891 0.0) "2" (textStyleRef "GostB-12") (extent 2.64582 5.02707) )
      ) 
      (pinName (text (pt 14.732 0.0) "" (textStyleRef "GostB-12") (justify Right) (extent 0.79374 0.79374) )
      ) 
    )
    (line (pt 4.16 2.0) (pt 4.16 -2.0) )
    (line (pt 4.16 0.0) (pt 0.0 0.0) )
    (line (pt 14.16 -2.0) (pt 14.16 2.0) )
    (line (pt 14.16 0.0) (pt 17.78 0.0) )
    (line (pt 4.16 -2.0) (pt 14.16 -2.0) )
    (line (pt 14.16 2.0) (pt 4.16 2.0) )
    (attr "Value" "" (rotation 270.0) (textStyleRef "GostB-12") )
    (attr "Type" "" (pt 10.16 -5.08) (justify UpperCenter) (textStyleRef "GostB-12") )
    (attr "RefDes" "" (pt 10.22 -3.88) (rotation 180.0) (isVisible True) (justify LowerCenter) (textStyleRef "GostB-12") )
  )
  (symbolDef "CONTROL_POINT_1_1"
    (originalName "CONTROL_POINT_1")
    (pin (pinNum 1) (pt 0.0 0.0) (pinLength 0.05) 
      (pinDisplay (dispPinDes False) ) 
      (pinDes (text (pt 1.651 0.0) "1" (textStyleRef "H4.00") (extent 2.91041 5.02707) )
      ) 
      (pinName (text (pt -0.508 0.0) "1" (textStyleRef "H4.00") (justify Right) (extent 2.91041 5.02707) )
      ) 
      (defaultPinDes "1")
    )
    (triplePointArc (pt 0.0 0.0) (pt -0.6 0.0) (pt -0.6 0.0) (width 1.3) )
    (attr "RefDes" "" (pt 2.5 2.5) (isVisible True) (textStyleRef "GostB-12") )
    (attr "Type" "" (pt 2.5 0.0) (justify UpperLeft) (textStyleRef "H4.00") )
  )
  (compDef "HSMX-H670_1"
    (originalName "HSMX-H670")
    (compHeader 
      (sourceLibrary "STEPAN.LIB")
      (numPins 2)
      (numParts 1)
      (alts (ieeeAlt False) (deMorganAlt False))
      (refDesPrefix "H")
    )
    (compPin "1" (pinName "A") (partNum 1) (symPinNum 1) (gateEq 1) (pinEq 0) )
    (compPin "2" (pinName "K") (partNum 1) (symPinNum 2) (gateEq 1) (pinEq 0) )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "HL1") )
    (attachedPattern (patternNum 1) (patternName "KP-2012")
      (numPads 2)
      (padPinMap 
        (padNum  1) (compPinRef "1")
        (padNum  2) (compPinRef "2")
      )
    )
  )
  (compDef "CR0603-JW-XXXE_1"
    (originalName "CR0603-JW-XXXE")
    (compHeader 
      (sourceLibrary "STEPAN.LIB")
      (numPins 2)
      (numParts 1)
      (alts (ieeeAlt False) (deMorganAlt False))
      (refDesPrefix "R")
      (numType Numeric)
    )
    (compPin "1" (partNum 1) (symPinNum 1) (gateEq 1) (pinEq 0) )
    (compPin "2" (partNum 1) (symPinNum 2) (gateEq 1) (pinEq 0) )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "R_CONST") )
    (attachedPattern (patternNum 1) (patternName "0603(0.8X1.6)")
      (numPads 2)
      (padPinMap 
        (padNum  1) (compPinRef "1")
        (padNum  2) (compPinRef "2")
      )
    )
  )
  (compDef "KONTAKT_1"
    (originalName "KONTAKT")
    (compHeader 
      (sourceLibrary "STEPAN.LIB")
      (numPins 1)
      (numParts 1)
      (alts (ieeeAlt False) (deMorganAlt False))
      (refDesPrefix " ")
    )
    (compPin "1" (pinName "1") (partNum 1) (symPinNum 1) (gateEq 1) (pinEq 0) )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "CONTROL_POINT_1") )
    (attachedPattern (patternNum 1) (patternName "KONTAKT")
      (numPads 1)
      (padPinMap 
        (padNum  1) (compPinRef "1")
      )
    )
  )
)

(netlist "Netlist_1"
  (compInst "8"
    (compRef "KONTAKT_1")
    (originalName "KONTAKT")
    (patternName "KONTAKT")
  )
  (compInst "6"
    (compRef "KONTAKT_1")
    (originalName "KONTAKT")
    (patternName "KONTAKT")
  )
  (compInst "7"
    (compRef "KONTAKT_1")
    (originalName "KONTAKT")
    (patternName "KONTAKT")
  )
  (compInst "5"
    (compRef "KONTAKT_1")
    (originalName "KONTAKT")
    (patternName "KONTAKT")
  )
  (compInst "3"
    (compRef "KONTAKT_1")
    (originalName "KONTAKT")
    (patternName "KONTAKT")
  )
  (compInst "1"
    (compRef "KONTAKT_1")
    (originalName "KONTAKT")
    (patternName "KONTAKT")
  )
  (compInst "2"
    (compRef "KONTAKT_1")
    (originalName "KONTAKT")
    (patternName "KONTAKT")
  )
  (compInst "4"
    (compRef "KONTAKT_1")
    (originalName "KONTAKT")
    (patternName "KONTAKT")
  )
  (compInst "R4"
    (compRef "CR0603-JW-XXXE_1")
    (originalName "CR0603-JW-XXXE")
    (compValue "(CR0603±5 % W-390 Ом)\\CR0603-JW-391E\\Bourns")
    (patternName "0603(0.8X1.6)")
  )
  (compInst "R3"
    (compRef "CR0603-JW-XXXE_1")
    (originalName "CR0603-JW-XXXE")
    (compValue "(CR0603±5 % W-390 Ом)\\CR0603-JW-391E\\Bourns")
    (patternName "0603(0.8X1.6)")
  )
  (compInst "R1"
    (compRef "CR0603-JW-XXXE_1")
    (originalName "CR0603-JW-XXXE")
    (compValue "(CR0603±5 % W-390 Ом)\\CR0603-JW-391E\\Bourns")
    (patternName "0603(0.8X1.6)")
  )
  (compInst "R2"
    (compRef "CR0603-JW-XXXE_1")
    (originalName "CR0603-JW-XXXE")
    (compValue "(CR0603±5 % W-390 Ом)\\CR0603-JW-391E\\Bourns")
    (patternName "0603(0.8X1.6)")
  )
  (compInst "H1"
    (compRef "HSMX-H670_1")
    (originalName "HSMX-H670")
    (compValue "\\Светодиод KP-2012SGC\\Kingbright")
    (patternName "KP-2012")
  )
  (compInst "H5"
    (compRef "HSMX-H670_1")
    (originalName "HSMX-H670")
    (compValue "\\Светодиод KP-2012SGC\\Kingbright")
    (patternName "KP-2012")
  )
  (compInst "H3"
    (compRef "HSMX-H670_1")
    (originalName "HSMX-H670")
    (compValue "\\Светодиод KP-2012SGC\\Kingbright")
    (patternName "KP-2012")
  )
  (compInst "H4"
    (compRef "HSMX-H670_1")
    (originalName "HSMX-H670")
    (compValue "\\Светодиод KP-2012SGC\\Kingbright")
    (patternName "KP-2012")
  )
  (compInst "H6"
    (compRef "HSMX-H670_1")
    (originalName "HSMX-H670")
    (compValue "\\Светодиод KP-2012SGC\\Kingbright")
    (patternName "KP-2012")
  )
  (compInst "H2"
    (compRef "HSMX-H670_1")
    (originalName "HSMX-H670")
    (compValue "\\Светодиод KP-2012EC\\Kingbright")
    (patternName "KP-2012")
  )
  (net "NET00000"
    (node "H3" "1")
    (node "H5" "1")
    (node "H4" "1")
    (node "H6" "1")
    (node "7" "1")
  )
  (net "NET00008"
    (node "H5" "2")
    (node "R1" "1")
  )
  (net "NET00009"
    (node "H6" "2")
    (node "R2" "1")
  )
  (net "NET00003"
    (node "R3" "2")
    (node "5" "1")
  )
  (net "NET00004"
    (node "R4" "2")
    (node "6" "1")
  )
  (net "NET00005"
    (node "H2" "2")
    (node "H1" "2")
    (node "8" "1")
  )
  (net "NET00006"
    (node "H1" "1")
    (node "R3" "1")
  )
  (net "NET00007"
    (node "H2" "1")
    (node "R4" "1")
  )
  (net "NET00001"
    (node "H4" "2")
    (node "2" "1")
  )
  (net "NET00002"
    (node "H3" "2")
    (node "1" "1")
  )
  (net "NET00010"
    (node "R2" "2")
    (node "4" "1")
  )
  (net "NET00011"
    (node "R1" "2")
    (node "3" "1")
  )
)

(schematicDesign "SchDesign_1"
  (schDesignHeader 
    (workspaceSize 1289.0 941.5)
    (gridDfns 
      (grid "0.001")
      (grid "0.010")
      (grid "0.050")
      (grid "0.100")
      (grid "0.254")
      (grid "0.500")
      (grid "1.000")
      (grid "1.270")
      (grid "2.000")
      (grid "2.540")
    )
    (designInfo 
      (fieldSet "(Default)"
        (fieldDef "Date" "  ")
        (fieldDef "Time" "  ")
        (fieldDef "Author" "  ")
        (fieldDef "Revision" "  ")
        (fieldDef "Title" "  ")
        (fieldDef "Approved By" "  ")
        (fieldDef "Checked By" "  ")
        (fieldDef "Company Name" "  ")
        (fieldDef "Drawing Number" "  ")
        (fieldDef "Drawn By" "  ")
        (fieldDef "Engineer" "  ")
        (fieldDef "Variant Name" "")
        (fieldDef "Variant Description" "")
        (fieldDef "Engineer1" "  ")
        (fieldDef "Title1" "  ")
        (fieldDef "Дата" "{Дата}")
        (fieldDef "Дец. номер 1" "  ")
        (fieldDef "Дец. номер 2" "{Дец. номер 2}")
        (fieldDef "Копировал" "  ")
        (fieldDef "Лист" "  ")
        (fieldDef "Листов" "{Листов}")
        (fieldDef "Н. контр." "{Н. контр.}")
        (fieldDef "Наим. изд 1" "{Наим. изд 1}")
        (fieldDef "Наим. изд. 2" "{Наим. изд. 2}")
        (fieldDef "Наименов. документа" "{Наименов. документа}")
        (fieldDef "Пров." "{Пров.}")
        (fieldDef "Разраб." "{Разраб.}")
        (fieldDef "Утв." "{Утв.}")
      )
    )
    (refPointSize 2.54)
    (infoPointSize 2.54)
    (junctionSize 1.0)
    (refPointSizePrint 2.54)
    (infoPointSizePrint 2.54)
    (junctionSizePrint 1.0)
  )
  (titleSheet 
     ""
    1.0000 
    (isVisible True)
    (offset 0.0 0.0)
    (border
      (isVisible False)
      (height 916.1)
      (width 1263.6)
      (offset 12.7 12.7)
    )
    (zones
      (isVisible False) 
      (textStyleRef "(Default)") 
      (horizontalZones 1
        (numDirection ascending)
        (numType Alphabetic)
      )
      (verticalZones 1 
        (numDirection ascending)
        (numType Numeric)
      ) 
    ) 
  )
  (sheet "sch1" (sheetNum 9)
    (titleSheet 
       ""
      1.0000 
      (isVisible True)
      (offset 0.0 0.0)
      (border
        (isVisible False)
        (height 915.6)
        (width 1263.6)
        (offset 12.7 12.7)
      )
      (zones
        (isVisible False) 
        (textStyleRef "(Default)") 
        (horizontalZones 1
          (numDirection ascending)
          (numType Alphabetic)
        )
        (verticalZones 1 
          (numDirection ascending)
          (numType Numeric)
        ) 
      ) 
    )
    (fieldSetRef "(Default)")
    (line (pt 1066.14 12.86) (pt 1066.24 12.86) (width 0.1) )
    (line (pt 1066.14 12.86) (pt 1066.14 12.96) (width 0.1) )
    (line (pt 1066.14 309.86) (pt 1066.24 309.86) (width 0.1) )
    (line (pt 1066.14 309.76) (pt 1066.14 309.86) (width 0.1) )
    (triplePointArc (pt 1092.682 79.292) (pt 1091.557 79.292) (pt 1091.557 79.292) (width 0.254) )
    (triplePointArc (pt 1092.682 79.292) (pt 1091.782 79.292) (pt 1091.782 79.292) (width 0.254) )
    (triplePointArc (pt 1092.682 79.292) (pt 1091.982 79.292) (pt 1091.982 79.292) (width 0.254) )
    (triplePointArc (pt 1092.682 79.292) (pt 1092.422 79.292) (pt 1092.422 79.292) (width 0.254) )
    (triplePointArc (pt 1092.682 79.292) (pt 1092.182 79.292) (pt 1092.182 79.292) (width 0.254) )
    (triplePointArc (pt 1092.682 79.292) (pt 1092.582 79.292) (pt 1092.582 79.292) (width 0.254) )
    (text (pt 1220.8 101.25) "4" (textStyleRef "GostB-12") (extent 2.91041 5.02707) )
    (text (pt 1220.22 116.94) "4" (textStyleRef "GostB-12") (extent 2.91041 5.02707) )
    (junction (pt 1238.24 238.4) (netNameRef "NET00000") )
    (junction (pt 1238.24 255.4) (netNameRef "NET00000") )
    (line (pt 1276.04 12.86) (pt 1276.14 12.86) (width 0.1) )
    (line (pt 1276.14 12.86) (pt 1276.14 12.96) (width 0.1) )
    (line (pt 1276.04 309.86) (pt 1276.14 309.86) (width 0.1) )
    (line (pt 1276.14 309.76) (pt 1276.14 309.86) (width 0.1) )
    (text (pt 1091.942 81.572) "1" (textStyleRef "GostB-12") (extent 2.11666 5.02707) )
    (text (pt 1220.22 132.94) "1" (textStyleRef "GostB-12") (extent 2.11666 5.02707) )
    (wire (line (pt 1238.24 273.4) (pt 1238.24 255.4) (width 0.255) (netNameRef "NET00000") )
    )
    (junction (pt 1238.24 273.4) (netNameRef "NET00000") )
    (text (pt 1220.22 124.94) "1" (textStyleRef "GostB-12") (extent 2.11666 5.02707) )
    (wire (line (pt 1226.24 221.4) (pt 1226.24 204.4) (width 0.255) (netNameRef "NET00005") )
    )
    (wire (line (pt 1226.24 204.4) (pt 1226.24 174.4) (width 0.255) (netNameRef "NET00005") )
    )
    (wire (line (pt 1238.24 255.4) (pt 1238.24 238.4) (width 0.255) (netNameRef "NET00000") )
    )
    (wire (line (pt 1238.24 189.4) (pt 1238.24 238.4) (width 0.255) (netNameRef "NET00000") )
    )
    (wire (line (pt 1238.24 290.4) (pt 1238.24 273.4) (width 0.255) (netNameRef "NET00000") )
    )
    (line (pt 1086.07 162.31) (pt 1086.07 91.19) )
    (line (pt 1105.47 162.31) (pt 1105.47 91.2) )
    (line (pt 1215.9 162.31) (pt 1215.9 91.23) )
    (line (pt 1226.1114 162.3054) (pt 1226.11 91.2) )
    (line (pt 1271.07 162.31) (pt 1271.07 91.19) )
    (line (pt 1092.682 79.292) (pt 1099.682 79.292) )
    (text (pt 1089.09 116.94) "H3- H6" (textStyleRef "GostB-12") (extent 12.17082 5.02707) )
    (text (pt 1114.9 101.45) "Резистор " (textStyleRef "GostB-12") (extent 15.87499 5.02707) )
    (text (pt 1133.26 101.3) "CR0603-JW-391E" (textStyleRef "GostB-12") (extent 27.25207 5.02707) )
    (text (pt 1177.8 101.25) "Bourns" (textStyleRef "GostB-12") (extent 11.90624 5.02707) )
    (junction (pt 1226.24 204.4) (netNameRef "NET00005") )
    (wire (line (pt 1230.24 238.4) (pt 1238.24 238.4) (width 0.255) (netNameRef "NET00000") )
    )
    (wire (line (pt 1230.24 255.4) (pt 1238.24 255.4) (width 0.255) (netNameRef "NET00000") )
    )
    (wire (line (pt 1230.24 273.4) (pt 1238.24 273.4) (width 0.255) (netNameRef "NET00000") )
    )
    (wire (line (pt 1230.24 290.4) (pt 1238.24 290.4) (width 0.255) (netNameRef "NET00000") )
    )
    (text (pt 1089.09 132.94) "H1" (textStyleRef "GostB-12") (extent 4.23332 5.02707) )
    (symbol (symbolRef "CONTROL_POINT_1_1") (refDesRef "8") (partNum 1) (pt 1124.24 174.4) )
    (symbol (symbolRef "CONTROL_POINT_1_1") (refDesRef "7") (partNum 1) (pt 1124.24 189.4) )
    (symbol (symbolRef "CONTROL_POINT_1_1") (refDesRef "6") (partNum 1) (pt 1124.24 204.4) )
    (symbol (symbolRef "CONTROL_POINT_1_1") (refDesRef "5") (partNum 1) (pt 1124.24 221.4) )
    (symbol (symbolRef "CONTROL_POINT_1_1") (refDesRef "4") (partNum 1) (pt 1124.24 238.4) )
    (symbol (symbolRef "CONTROL_POINT_1_1") (refDesRef "3") (partNum 1) (pt 1124.24 255.4) )
    (symbol (symbolRef "CONTROL_POINT_1_1") (refDesRef "1") (partNum 1) (pt 1124.24 290.4) )
    (text (pt 1134.43 173.73) "GND" (textStyleRef "GostB-12") (extent 7.14374 5.02707) )
    (text (pt 1133.16 188.89) "+3.3V" (textStyleRef "GostB-12") (extent 9.52499 5.02707) )
    (symbol (symbolRef "R_CONST_1") (refDesRef "R4") (partNum 1) (pt 1186.24 204.4) (rotation 180.0) )
    (symbol (symbolRef "R_CONST_1") (refDesRef "R3") (partNum 1) (pt 1186.24 221.4) (rotation 180.0) 
      (attr "RefDes" "" (pt -10.22 2.12) (isVisible True) (justify LowerCenter) (textStyleRef "GostB-12") )
    )
    (symbol (symbolRef "R_CONST_1") (refDesRef "R2") (partNum 1) (pt 1186.24 238.4) (rotation 180.0) 
      (attr "RefDes" "" (pt -10.22 2.9) (isVisible True) (justify LowerCenter) (textStyleRef "GostB-12") )
    )
    (symbol (symbolRef "R_CONST_1") (refDesRef "R1") (partNum 1) (pt 1186.24 255.4) (rotation 180.0) 
      (attr "RefDes" "" (pt -10.22 3.68) (isVisible True) (justify LowerCenter) (textStyleRef "GostB-12") )
    )
    (symbol (symbolRef "HL1_1") (refDesRef "H2") (partNum 1) (pt 1201.24 204.4) )
    (text (pt 1089.09 124.94) "H2" (textStyleRef "GostB-12") (extent 4.76249 5.02707) )
    (symbol (symbolRef "CONTROL_POINT_1_1") (refDesRef "2") (partNum 1) (pt 1124.24 273.4) )
    (symbol (symbolRef "HL1_2") (refDesRef "H1") (partNum 1) (pt 1201.24 221.4) )
    (text (pt 1089.67 101.25) "R1- R4" (textStyleRef "GostB-12") (extent 11.90624 5.02707) )
    (text (pt 1119.8 93.25) "(CR0603±5 % W-390 Ом)" (textStyleRef "GostB-12") (extent 41.80416 5.02707) )
    (text (pt 1119.22 116.94) "KP-2012SGC" (textStyleRef "GostB-12") (extent 19.84374 5.02707) )
    (line (pt 1130.86 140.99) (pt 1170.42 141.0) )
    (wire (line (pt 1124.29 174.4) (pt 1226.24 174.4) (width 0.255) (netNameRef "NET00005") )
    )
    (wire (line (pt 1186.24 204.4) (pt 1201.24 204.4) (width 0.255) (netNameRef "NET00007") )
    )
    (wire (line (pt 1216.48 204.4) (pt 1226.24 204.4) (width 0.255) (netNameRef "NET00005") )
    )
    (wire (line (pt 1168.46 204.4) (pt 1124.29 204.4) (width 0.255) (netNameRef "NET00004") )
    )
    (wire (line (pt 1186.24 221.4) (pt 1201.24 221.4) (width 0.255) (netNameRef "NET00006") )
    )
    (wire (line (pt 1216.48 221.4) (pt 1226.24 221.4) (width 0.255) (netNameRef "NET00005") )
    )
    (wire (line (pt 1168.46 221.4) (pt 1124.29 221.4) (width 0.255) (netNameRef "NET00003") )
    )
    (wire (line (pt 1215.0 238.4) (pt 1186.24 238.4) (width 0.255) (netNameRef "NET00009") )
    )
    (text (pt 1131.89 238.1) "~LINKLED1" (textStyleRef "GostB-12") (extent 14.81666 5.02707) )
    (wire (line (pt 1168.46 238.4) (pt 1124.29 238.4) (width 0.255) (netNameRef "NET00010") )
    )
    (wire (line (pt 1215.0 255.4) (pt 1186.24 255.4) (width 0.255) (netNameRef "NET00008") )
    )
    (wire (line (pt 1168.46 255.4) (pt 1124.29 255.4) (width 0.255) (netNameRef "NET00011") )
    )
    (wire (line (pt 1215.0 273.4) (pt 1124.29 273.4) (width 0.255) (netNameRef "NET00001") )
    )
    (text (pt 1131.89 291.26) "~LANLED0" (textStyleRef "GostB-12") (extent 14.81666 5.02707) )
    (wire (line (pt 1124.29 290.4) (pt 1215.0 290.4) (width 0.255) (netNameRef "NET00002") )
    )
    (text (pt 1119.22 132.94) "KP-2012SGC" (textStyleRef "GostB-12") (extent 19.84374 5.02707) )
    (text (pt 1130.74 141.24) "Светодиоды " (textStyleRef "GostB-12") (extent 20.10832 5.02707) )
    (text (pt 1154.01 141.24) "Kingbright" (textStyleRef "GostB-12") (extent 16.93332 5.02707) )
    (text (pt 1149.24 204.4) "POWER_LED" (textStyleRef "GostB-12") (isFlipped True) (extent 19.31457 5.02707) )
    (text (pt 1144.59 221.21) "HDD_LED" (textStyleRef "GostB-12") (isFlipped True) (extent 14.55207 5.02707) )
    (text (pt 1131.89 255.26) "~LANLED1" (textStyleRef "GostB-12") (extent 14.28749 5.02707) )
    (symbol (symbolRef "HL1_3") (refDesRef "H5") (partNum 1) (pt 1230.24 255.4) (isFlipped True))
    (symbol (symbolRef "HL1_3") (refDesRef "H3") (partNum 1) (pt 1230.24 290.4) (isFlipped True))
    (text (pt 1090.1422 147.675) "Поз.\r\nобозна-\r\nчение " (textStyleRef "GostB-14") (extent 16.00729 15.74271) )
    (text (pt 1119.22 124.94) "KP-2012EC" (textStyleRef "GostB-12") (extent 17.46249 5.02707) )
    (symbol (symbolRef "HL1_3") (refDesRef "H6") (partNum 1) (pt 1230.24 238.4) (isFlipped True))
    (text (pt 1217.2722 152.755) "Кол." (textStyleRef "GostB-14") (extent 8.59896 5.86493) )
    (text (pt 1146.1522 152.755) "Наименование " (textStyleRef "GostB-18") (extent 37.70312 7.54062) )
    (text (pt 1131.89 274.1) "~LINKLED0" (textStyleRef "GostB-12") (extent 15.34582 5.02707) )
    (symbol (symbolRef "HL1_3") (refDesRef "H4") (partNum 1) (pt 1230.24 273.4) (isFlipped True))
    (line (pt 1086.07 91.19) (pt 1271.07 91.19) )
    (line (pt 1086.1574 99.3134) (pt 1271.0694 99.3134) )
    (line (pt 1086.1574 107.4414) (pt 1271.0694 107.4414) )
    (line (pt 1086.1574 115.3154) (pt 1271.0694 115.3154) )
    (line (pt 1086.1574 123.1894) (pt 1271.0694 123.1894) )
    (line (pt 1086.1574 131.3174) (pt 1271.0694 131.3174) )
    (line (pt 1086.1574 139.1914) (pt 1271.0694 139.1914) )
    (line (pt 1086.1574 147.3194) (pt 1271.0694 147.3194) )
    (line (pt 1086.07 162.31) (pt 1271.07 162.31) )
    (wire (line (pt 1124.29 189.4) (pt 1238.24 189.4) (width 0.255) (netNameRef "NET00000") )
    )
    (text (pt 1084.322 79.032) "            (точка с цифрой) - условное обозначение паяного контакта." (textStyleRef "GostB-14") (extent 143.27187 5.86493) )
    (text (pt 1237.5922 152.755) "Примечание " (textStyleRef "GostB-14") (extent 25.00312 5.86493) )
    (drawBorder True)
    (EntireDesign True)
    (isRotated False)
    (pageSize User)
    (scaleFactor  0.65)
    (offset 0.0 0.0)
    (PrintRegion 
      (pt 26.099 10.033) (pt 830.527 566.928) )
    (sheetOrderNum 1)
  )
  (sheet "Sheet1" (sheetNum 1)
    (fieldSetRef "(Default)")
    (drawBorder True)
    (EntireDesign True)
    (isRotated False)
    (pageSize Size_A)
    (scaleFactor  1.00)
    (offset 0.0 0.0)
    (PrintRegion 
      (pt 0.0 0.0) (pt 0.0 0.0) )
    (sheetOrderNum 2)
  )
  (schematicPrintSettings 
    (sheetList 
    )
  )

  (programState 
    (layerState 
      (currentLayer (layerNumRef 9))
    )
    (gridState 
      (currentAbsGrid "0.010")
      (currentRelGrid "2.540")
      (isAbsoluteGrid True)
      (isDottedGrid True)
      (isVisibleGrid True)
      (isPromptForRel False)
    )
    (ecoState (ecoRecording True))
    (currentTextStyle "GostB-12")
  )

  (reportSettings 
    (reportStyle reportStyleComma)
    (reportDestination DestinationScreen)
    (pt 0.0 0.0) 
    (reportDefinitions 
      (reportDefinition 
        (reportName "Attributes")
        (reportExtension "atr")
        (reportType ReportTypeAttributes)
        (reportLinesPerPage 70)
        (reportColumnWidth 20)
        (reportHeader "")
        (reportFooter "")
        (reportShowCDFPreface True)
        (reportShowColumnNames True)
        (reportFieldsSections 
          (reportFields 
            (reportField 
              (reportFieldName "RefDes")
              (reportFieldType PropertyTypeRefdes)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 6)
            )
            (reportField 
              (reportFieldName "Type")
              (reportFieldType PropertyTypeType)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 4)
            )
            (reportField 
              (reportFieldName "Value")
              (reportFieldType PropertyTypeCompValue)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 5)
            )
          )
          (reportFields 
            (reportField 
              (reportFieldName "NetName")
              (reportFieldType PropertyTypeNetname)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 7)
            )
          )
        )
      )
      (reportDefinition 
        (reportName "Bill of Materials")
        (reportExtension "bom")
        (reportShowFlag True)
        (reportType ReportTypeBillOfMaterials)
        (reportLinesPerPage 62)
        (reportColumnWidth 15)
        (reportHeader "")
        (reportFooter "")
        (reportFieldsSections 
          (reportFields 
            (reportField 
              (reportFieldName "RefDes")
              (reportFieldType PropertyTypeRefdes)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 6)
            )
            (reportField 
              (reportFieldName "_Count")
              (reportFieldType PropertyTypeCount)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 6)
            )
            (reportField 
              (reportFieldName "ComponentName")
              (reportFieldType PropertyTypeComponentName)
              (reportFieldSortOrder 2)
              (reportFieldSortType ascending)
              (reportFieldColumnWidth 13)
            )
            (reportField 
              (reportFieldName "PatternName")
              (reportFieldType PropertyTypePatternName)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldColumnWidth 11)
            )
            (reportField 
              (reportFieldName "Value")
              (reportFieldType PropertyTypeCompValue)
              (reportFieldSortOrder 3)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 5)
            )
            (reportField 
              (reportFieldName "Plus")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldColumnWidth 4)
            )
          )
        )
      )
      (reportDefinition 
        (reportName "Global Nets")
        (reportExtension "gnr")
        (reportType ReportTypeGlobalNets)
        (reportLinesPerPage 62)
        (reportColumnWidth 15)
        (reportHeader "")
        (reportFooter "")
        (reportShowCDFPreface True)
        (reportShowColumnNames True)
        (reportFieldsSections 
          (reportFields 
            (reportField 
              (reportFieldName "NetName")
              (reportFieldType PropertyTypeNetname)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 7)
            )
            (reportField 
              (reportFieldName "SheetNum")
              (reportFieldType PropertyTypeSheetnumber)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 8)
            )
          )
        )
      )
      (reportDefinition 
        (reportName "Last Used RefDes")
        (reportExtension "lud")
        (reportType ReportTypeLastRefdes)
        (reportLinesPerPage 62)
        (reportColumnWidth 15)
        (reportHeader "")
        (reportFooter "")
        (reportShowCDFPreface True)
        (reportShowColumnNames True)
        (reportFieldsSections 
          (reportFields 
            (reportField 
              (reportFieldName "RefDes")
              (reportFieldType PropertyTypeRefdes)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 6)
            )
            (reportField 
              (reportFieldName "Value")
              (reportFieldType PropertyTypeCompValue)
              (reportFieldSortOrder 2)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 5)
            )
          )
        )
      )
      (reportDefinition 
        (reportName "Library Contents")
        (reportExtension "lct")
        (reportType ReportTypeLibrary)
        (reportLinesPerPage 62)
        (reportColumnWidth 15)
        (reportHeader "")
        (reportFooter "")
        (reportShowCDFPreface True)
        (reportShowColumnNames True)
      )
      (reportDefinition 
        (reportName "Parts Locations")
        (reportExtension "plc")
        (reportType ReportTypePartsLocations)
        (reportLinesPerPage 62)
        (reportColumnWidth 15)
        (reportHeader "")
        (reportFooter "")
        (reportShowCDFPreface True)
        (reportShowColumnNames True)
        (reportFieldsSections 
          (reportFields 
            (reportField 
              (reportFieldName "RefDes")
              (reportFieldType PropertyTypeRefdes)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 6)
            )
            (reportField 
              (reportFieldName "SheetNum")
              (reportFieldType PropertyTypeSheetnumber)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 8)
            )
            (reportField 
              (reportFieldName "LocationX")
              (reportFieldType PropertyTypeLocationX)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 9)
            )
            (reportField 
              (reportFieldName "LocationY")
              (reportFieldType PropertyTypeLocationY)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 9)
            )
            (reportField 
              (reportFieldName "Rotation")
              (reportFieldType PropertyTypeRotation)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 8)
            )
          )
        )
      )
      (reportDefinition 
        (reportName "Parts Usage")
        (reportExtension "ptu")
        (reportType ReportTypePartsUsage)
        (reportLinesPerPage 62)
        (reportColumnWidth 15)
        (reportHeader "")
        (reportFooter "")
        (reportShowCDFPreface True)
        (reportShowColumnNames True)
        (reportFieldsSections 
          (reportFields 
            (reportField 
              (reportFieldName "RefDes")
              (reportFieldType PropertyTypeRefdes)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 6)
            )
            (reportField 
              (reportFieldName "Type")
              (reportFieldType PropertyTypeType)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 4)
            )
            (reportField 
              (reportFieldName "Unused Parts")
              (reportFieldType PropertyTypeUnusedParts)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 12)
            )
            (reportField 
              (reportFieldName "ComponentLibrary")
              (reportFieldType PropertyTypeComponentLibrary)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 16)
            )
          )
        )
      )
      (reportDefinition 
        (reportName "Variant")
        (reportExtension "var")
        (reportType ReportTypeVariant)
        (reportLinesPerPage 60)
        (reportColumnWidth 35)
        (reportHeader "")
        (reportFooter "")
        (reportShowCDFPreface True)
        (reportShowColumnNames True)
        (reportFieldsSections 
          (reportFields 
            (reportField 
              (reportFieldName "Variant")
              (reportFieldType PropertyTypeVariant)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 7)
            )
            (reportField 
              (reportFieldName "Variant Decription")
              (reportFieldType PropertyTypeVariantDescription)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 18)
            )
            (reportField 
              (reportFieldName "Variant Excluded Components")
              (reportFieldType PropertyTypeExcludedComponents)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 27)
            )
          )
        )
      )
    )
  )
)
